name: Deploy to Live Server

on:
  push:
    branches:
      - current-release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm install
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: replace

      - name: Backup database before deployment
        run: ssh -i ~/.ssh/id_rsa vulps@161.97.68.166 'cd /var/gamesync-bot && ./backup.sh'

      - name: Copy files
        run: |
          rsync -av --exclude='node_modules' . vulps@161.97.68.166:/var/gamesync-bot
          scp -i ~/.ssh/id_rsa package.json vulps@161.97.68.166:/var/gamesync-bot
          ssh -i ~/.ssh/id_rsa vulps@161.97.68.166 'cd /var/gamesync-bot && chmod +x backup.sh'

      - name: Install dependencies on server and reload
        run: ssh -i ~/.ssh/id_rsa vulps@161.97.68.166 'cd /var/gamesync-bot && npm install --omit=dev --update-env && pm2 reload all'
